/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as VipRouteImport } from './routes/vip'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MyBetsRouteImport } from './routes/my-bets'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveRouteImport } from './routes/live'
import { Route as BetslipRouteImport } from './routes/betslip'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCreateWalletRouteImport } from './routes/api/create-wallet'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const VipRoute = VipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBetsRoute = MyBetsRouteImport.update({
  id: '/my-bets',
  path: '/my-bets',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const BetslipRoute = BetslipRouteImport.update({
  id: '/betslip',
  path: '/betslip',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreateWalletRoute = ApiCreateWalletRouteImport.update({
  id: '/api/create-wallet',
  path: '/api/create-wallet',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/betslip': typeof BetslipRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/my-bets': typeof MyBetsRoute
  '/profile': typeof ProfileRoute
  '/vip': typeof VipRoute
  '/wallet': typeof WalletRoute
  '/api/create-wallet': typeof ApiCreateWalletRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/betslip': typeof BetslipRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/my-bets': typeof MyBetsRoute
  '/profile': typeof ProfileRoute
  '/vip': typeof VipRoute
  '/wallet': typeof WalletRoute
  '/api/create-wallet': typeof ApiCreateWalletRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/betslip': typeof BetslipRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/my-bets': typeof MyBetsRoute
  '/profile': typeof ProfileRoute
  '/vip': typeof VipRoute
  '/wallet': typeof WalletRoute
  '/api/create-wallet': typeof ApiCreateWalletRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/betslip'
    | '/live'
    | '/login'
    | '/my-bets'
    | '/profile'
    | '/vip'
    | '/wallet'
    | '/api/create-wallet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/betslip'
    | '/live'
    | '/login'
    | '/my-bets'
    | '/profile'
    | '/vip'
    | '/wallet'
    | '/api/create-wallet'
  id:
    | '__root__'
    | '/'
    | '/betslip'
    | '/live'
    | '/login'
    | '/my-bets'
    | '/profile'
    | '/vip'
    | '/wallet'
    | '/api/create-wallet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BetslipRoute: typeof BetslipRoute
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  MyBetsRoute: typeof MyBetsRoute
  ProfileRoute: typeof ProfileRoute
  VipRoute: typeof VipRoute
  WalletRoute: typeof WalletRoute
  ApiCreateWalletRoute: typeof ApiCreateWalletRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vip': {
      id: '/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof VipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bets': {
      id: '/my-bets'
      path: '/my-bets'
      fullPath: '/my-bets'
      preLoaderRoute: typeof MyBetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/betslip': {
      id: '/betslip'
      path: '/betslip'
      fullPath: '/betslip'
      preLoaderRoute: typeof BetslipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-wallet': {
      id: '/api/create-wallet'
      path: '/api/create-wallet'
      fullPath: '/api/create-wallet'
      preLoaderRoute: typeof ApiCreateWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BetslipRoute: BetslipRoute,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  MyBetsRoute: MyBetsRoute,
  ProfileRoute: ProfileRoute,
  VipRoute: VipRoute,
  WalletRoute: WalletRoute,
  ApiCreateWalletRoute: ApiCreateWalletRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
