/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as VirtualRouteImport } from './routes/virtual'
import { Route as VipRouteImport } from './routes/vip'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MyBetsRouteImport } from './routes/my-bets'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveRouteImport } from './routes/live'
import { Route as BetslipRouteImport } from './routes/betslip'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchMatchIdRouteImport } from './routes/match.$matchId'
import { Route as HooksSettleRouteImport } from './routes/hooks/settle'
import { Route as ApiFixturesRouteImport } from './routes/api/fixtures'
import { Route as ApiFixtureDetailsRouteImport } from './routes/api/fixture-details'
import { Route as ApiDepositRouteImport } from './routes/api/deposit'
import { Route as ApiCreateWalletRouteImport } from './routes/api/create-wallet'
import { Route as ApiAdminRouteImport } from './routes/api/admin'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const VirtualRoute = VirtualRouteImport.update({
  id: '/virtual',
  path: '/virtual',
  getParentRoute: () => rootRouteImport,
} as any)
const VipRoute = VipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBetsRoute = MyBetsRouteImport.update({
  id: '/my-bets',
  path: '/my-bets',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const BetslipRoute = BetslipRouteImport.update({
  id: '/betslip',
  path: '/betslip',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchMatchIdRoute = MatchMatchIdRouteImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksSettleRoute = HooksSettleRouteImport.update({
  id: '/hooks/settle',
  path: '/hooks/settle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFixturesRoute = ApiFixturesRouteImport.update({
  id: '/api/fixtures',
  path: '/api/fixtures',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFixtureDetailsRoute = ApiFixtureDetailsRouteImport.update({
  id: '/api/fixture-details',
  path: '/api/fixture-details',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDepositRoute = ApiDepositRouteImport.update({
  id: '/api/deposit',
  path: '/api/deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreateWalletRoute = ApiCreateWalletRouteImport.update({
  id: '/api/create-wallet',
  path: '/api/create-wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRoute = ApiAdminRouteImport.update({
  id: '/api/admin',
  path: '/api/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/betslip': typeof BetslipRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/my-bets': typeof MyBetsRoute
  '/profile': typeof ProfileRoute
  '/vip': typeof VipRoute
  '/virtual': typeof VirtualRoute
  '/wallet': typeof WalletRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/create-wallet': typeof ApiCreateWalletRoute
  '/api/deposit': typeof ApiDepositRoute
  '/api/fixture-details': typeof ApiFixtureDetailsRoute
  '/api/fixtures': typeof ApiFixturesRoute
  '/hooks/settle': typeof HooksSettleRoute
  '/match/$matchId': typeof MatchMatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/betslip': typeof BetslipRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/my-bets': typeof MyBetsRoute
  '/profile': typeof ProfileRoute
  '/vip': typeof VipRoute
  '/virtual': typeof VirtualRoute
  '/wallet': typeof WalletRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/create-wallet': typeof ApiCreateWalletRoute
  '/api/deposit': typeof ApiDepositRoute
  '/api/fixture-details': typeof ApiFixtureDetailsRoute
  '/api/fixtures': typeof ApiFixturesRoute
  '/hooks/settle': typeof HooksSettleRoute
  '/match/$matchId': typeof MatchMatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/betslip': typeof BetslipRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/my-bets': typeof MyBetsRoute
  '/profile': typeof ProfileRoute
  '/vip': typeof VipRoute
  '/virtual': typeof VirtualRoute
  '/wallet': typeof WalletRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/create-wallet': typeof ApiCreateWalletRoute
  '/api/deposit': typeof ApiDepositRoute
  '/api/fixture-details': typeof ApiFixtureDetailsRoute
  '/api/fixtures': typeof ApiFixturesRoute
  '/hooks/settle': typeof HooksSettleRoute
  '/match/$matchId': typeof MatchMatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/betslip'
    | '/live'
    | '/login'
    | '/my-bets'
    | '/profile'
    | '/vip'
    | '/virtual'
    | '/wallet'
    | '/api/admin'
    | '/api/create-wallet'
    | '/api/deposit'
    | '/api/fixture-details'
    | '/api/fixtures'
    | '/hooks/settle'
    | '/match/$matchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/betslip'
    | '/live'
    | '/login'
    | '/my-bets'
    | '/profile'
    | '/vip'
    | '/virtual'
    | '/wallet'
    | '/api/admin'
    | '/api/create-wallet'
    | '/api/deposit'
    | '/api/fixture-details'
    | '/api/fixtures'
    | '/hooks/settle'
    | '/match/$matchId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/betslip'
    | '/live'
    | '/login'
    | '/my-bets'
    | '/profile'
    | '/vip'
    | '/virtual'
    | '/wallet'
    | '/api/admin'
    | '/api/create-wallet'
    | '/api/deposit'
    | '/api/fixture-details'
    | '/api/fixtures'
    | '/hooks/settle'
    | '/match/$matchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BetslipRoute: typeof BetslipRoute
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  MyBetsRoute: typeof MyBetsRoute
  ProfileRoute: typeof ProfileRoute
  VipRoute: typeof VipRoute
  VirtualRoute: typeof VirtualRoute
  WalletRoute: typeof WalletRoute
  ApiAdminRoute: typeof ApiAdminRoute
  ApiCreateWalletRoute: typeof ApiCreateWalletRoute
  ApiDepositRoute: typeof ApiDepositRoute
  ApiFixtureDetailsRoute: typeof ApiFixtureDetailsRoute
  ApiFixturesRoute: typeof ApiFixturesRoute
  HooksSettleRoute: typeof HooksSettleRoute
  MatchMatchIdRoute: typeof MatchMatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/virtual': {
      id: '/virtual'
      path: '/virtual'
      fullPath: '/virtual'
      preLoaderRoute: typeof VirtualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vip': {
      id: '/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof VipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bets': {
      id: '/my-bets'
      path: '/my-bets'
      fullPath: '/my-bets'
      preLoaderRoute: typeof MyBetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/betslip': {
      id: '/betslip'
      path: '/betslip'
      fullPath: '/betslip'
      preLoaderRoute: typeof BetslipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$matchId': {
      id: '/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/match/$matchId'
      preLoaderRoute: typeof MatchMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/settle': {
      id: '/hooks/settle'
      path: '/hooks/settle'
      fullPath: '/hooks/settle'
      preLoaderRoute: typeof HooksSettleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fixtures': {
      id: '/api/fixtures'
      path: '/api/fixtures'
      fullPath: '/api/fixtures'
      preLoaderRoute: typeof ApiFixturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fixture-details': {
      id: '/api/fixture-details'
      path: '/api/fixture-details'
      fullPath: '/api/fixture-details'
      preLoaderRoute: typeof ApiFixtureDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deposit': {
      id: '/api/deposit'
      path: '/api/deposit'
      fullPath: '/api/deposit'
      preLoaderRoute: typeof ApiDepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-wallet': {
      id: '/api/create-wallet'
      path: '/api/create-wallet'
      fullPath: '/api/create-wallet'
      preLoaderRoute: typeof ApiCreateWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin': {
      id: '/api/admin'
      path: '/api/admin'
      fullPath: '/api/admin'
      preLoaderRoute: typeof ApiAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BetslipRoute: BetslipRoute,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  MyBetsRoute: MyBetsRoute,
  ProfileRoute: ProfileRoute,
  VipRoute: VipRoute,
  VirtualRoute: VirtualRoute,
  WalletRoute: WalletRoute,
  ApiAdminRoute: ApiAdminRoute,
  ApiCreateWalletRoute: ApiCreateWalletRoute,
  ApiDepositRoute: ApiDepositRoute,
  ApiFixtureDetailsRoute: ApiFixtureDetailsRoute,
  ApiFixturesRoute: ApiFixturesRoute,
  HooksSettleRoute: HooksSettleRoute,
  MatchMatchIdRoute: MatchMatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
